{
 "title": "ProxyAuth",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A", "reducer": "mean", "type": "math" },
    {
     "expr": "count_over_time({level=\"info\"} |= `new token` [1m])",
     "legendFormat": "new_token"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({app=\"proxyauth\"} |= `new token` [1m])",
     "legendFormat": "new_token"
    },
    {
     "expr": "count_over_time({app=\"proxyauth\"} |= `is logged` [1m])",
     "legendFormat": "is logged"
    }
   ]
  },
  {
   "title": "Logs ProxyAuth",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"proxyauth\"}"
    }
   ]
  }
 ]
}